# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtWidgets,QtCore
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 462)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.lineEditInfo = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEditInfo.setGeometry(QtCore.QRect(210, 240, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.lineEditInfo.setFont(font)
        self.lineEditInfo.setText("")
        self.lineEditInfo.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditInfo.setObjectName("lineEditInfo")
        self.lineEditInfo_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEditInfo_2.setGeometry(QtCore.QRect(210, 170, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.lineEditInfo_2.setFont(font)
        self.lineEditInfo_2.setObjectName("lineEditInfo_2")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(120, 170, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(120, 240, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(200, 60, 171, 71))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 574, 17))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEditInfo.setPlaceholderText(_translate("MainWindow", "请输入密码"))
        self.lineEditInfo_2.setPlaceholderText(_translate("MainWindow", "请输入账号"))
        self.label.setText(_translate("MainWindow", "账号:"))
        self.label_2.setText(_translate("MainWindow", "密码:"))
        self.label_3.setText(_translate("MainWindow", "仓库物流管理系统"))




class Ui_user(object):
    def setupUi(self, user):
        user.setObjectName("user")
        user.resize(400, 300)
        self.scrollArea = QtWidgets.QScrollArea(user)
        self.scrollArea.setGeometry(QtCore.QRect(40, 30, 321, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 301, 311))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit = QtWidgets.QLineEdit(user)
        self.lineEdit.setGeometry(QtCore.QRect(40, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtonConn = QtWidgets.QPushButton(user)
        self.pushButtonConn.setGeometry(QtCore.QRect(280, 200, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButtonConn.setFont(font)
        self.pushButtonConn.setObjectName("pushButtonConn")

        self.retranslateUi(user)
        QtCore.QMetaObject.connectSlotsByName(user)

    def retranslateUi(self, user):
        _translate = QtCore.QCoreApplication.translate
        user.setWindowTitle(_translate("user", "Form"))
        self.lineEdit.setPlaceholderText(_translate("user", "请输入要查询表的名称"))
        self.pushButtonConn.setText(_translate("user", "查询"))
class Ui_manager(object):
    def setupUi(self, manager):
        manager.setObjectName("manager")
        manager.resize(514, 403)
        self.pushButtonConn = QtWidgets.QPushButton(manager)
        self.pushButtonConn.setGeometry(QtCore.QRect(310, 200, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButtonConn.setFont(font)
        self.pushButtonConn.setObjectName("pushButtonConn")
        self.pushButtonConn_2 = QtWidgets.QPushButton(manager)
        self.pushButtonConn_2.setGeometry(QtCore.QRect(90, 240, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButtonConn_2.setFont(font)
        self.pushButtonConn_2.setObjectName("pushButtonConn_2")
        self.pushButtonConn_3 = QtWidgets.QPushButton(manager)
        self.pushButtonConn_3.setGeometry(QtCore.QRect(310, 240, 80, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.pushButtonConn_3.setFont(font)
        self.pushButtonConn_3.setObjectName("pushButtonConn_3")
        self.scrollArea = QtWidgets.QScrollArea(manager)
        self.scrollArea.setGeometry(QtCore.QRect(90, 30, 301, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 301, 311))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit = QtWidgets.QLineEdit(manager)
        self.lineEdit.setGeometry(QtCore.QRect(90, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(manager)
        QtCore.QMetaObject.connectSlotsByName(manager)

    def retranslateUi(self, manager):
        _translate = QtCore.QCoreApplication.translate
        manager.setWindowTitle(_translate("manager", "Form"))
        self.pushButtonConn.setText(_translate("manager", "查询"))
        self.pushButtonConn_2.setText(_translate("manager", "添加"))
        self.pushButtonConn_3.setText(_translate("manager", "删除"))
        self.lineEdit.setPlaceholderText(_translate("manager", "请输入要查询表的名称"))
if __name__ == "__main__":
    QtCore.QCoreApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling)
    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QMainWindow()
    ui = Ui_manager()
    # 我这边是默认的Ui_MainWindow，要是你们自己有修改，这边要相应修改
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
